services:
  proxy:
    image: caddy:2@sha256:cef7fe17d4df3b0843eae25bed319d6140b1a7bb13ccef076f5f1783d5bca9b1
    restart: unless-stopped
    command: "caddy run --config /etc/caddy/Caddyfile"
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .pullpreview/Caddyfile:/etc/caddy/Caddyfile
      - "/data"

  web:
    build: .
    ports:
      - "3014"
    environment:
      NODE_ENV: production
