name: PullPreview
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: dev
    permissions:
      id-token: write
      contents: read
      statuses: write
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate env file
        env:
          PULLPREVIEW_PASSWORD: ${{ secrets.PULLPREVIEW_PASSWORD }}
        run: |
          echo "PASSWORD=$PULLPREVIEW_PASSWORD" >> .env
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubCopilotDeploy
          role-session-name: pullpreview
          aws-region: eu-west-2
      - uses: pullpreview/action@v6
        with:
          admins: 'samuelhwilliams,srh-sloan,sfount,marcusher'
          instance_type: micro
          proxy_tls: web:3014
